name: Linux

on: 
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: apt-get
      run: sudo apt-get update && sudo apt-get install -y libavcodec-dev libavutil-dev libswscale-dev libresample-dev
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        target: x86_64-unknown-linux-musl
    - name: Build binary
      run: cargo build --verbose --features "keyframe_image" --release --target x86_64-unknown-linux-musl
      env:
        RUST_BACKTRACE: 1
    - name: Strip binary (linux and macos)
      run: strip "target/x86_64-unknown-linux-musl/release/xlive"
    - name: Build archive
      shell: bash
      run: |
        mkdir archive
        cp LICENSE README.md conf.yaml archive/
        cd archive
        cp "../target/x86_64-unknown-linux-musl/release/xlive" ./
        tar -czf "xlive-linux.tar.gz" LICENSE README.md conf.yaml xlive
        
    - name: Upload archive
      uses: actions/upload-artifact@v1
      with:
        name: xlive-linux.tar.gz
        path: archive/xlive-linux.tar.gz
